<?php 
/* Esñol */

$crl[0]='22';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Sound: On/Off';
$crl[4]='Aceptar';
$crl[5]='Cancelar';
$crl[6]='Contraseña';
$crl[7]='Canbiar colores...';
$crl[8]='ENOJADO';
$crl[9]='ALEGRE';
$crl[10]='TRISTE';
$crl[11]='GRITO';
$crl[12]='SONRISA';
$crl[13]='OJITO';
$crl[14]='NEGRILLA';
$crl[15]='ITALICA';
$crl[16]='COLOR';
$crl[17]='Fecha / Hora';
$crl[18]='Usuario';
$crl[19]='Mensaje';
$crl[20]='HISTORIA (150 lines)';
$crl[21]='Esta pagina requiere un navegador que soporte frames.';
$crl[22]='Users Online';
$crl[23]='No Users Online...';
$crl[24]='Entrar como';
$crl[25]='Chat';
$crl[26]='Estas dentro del chat [Refrescar]';
$crl[27]='Historia';
$crl[28]='Estas dentro del Historial [Refrescar]';
$crl[29]='Salir';
$crl[30]='Estas fuera [Cambiar nick]';
$crl[31]='Limpiar';
$crl[32]='Limpiar el Chat y el Historial [Contraseña protejida]';
$crl[33]='Acerca';
$crl[34]='Refrescar: ';
?>