<?php
/* Danish */

$crl[0]='4';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Lyd: Til/Fra';
$crl[4]='Bekræft';
$crl[5]='Fortryd';
$crl[6]='Kodeord';
$crl[7]='Skift farver...';
$crl[8]='Vred';
$crl[9]='Fattet';
$crl[10]='Nedtrykt';
$crl[11]='Råber';
$crl[12]='Smiler';
$crl[13]='Vinker';
$crl[14]='Fed';
$crl[15]='Skrå';
$crl[16]='Farver';
$crl[17]='Dato / Tid';
$crl[18]='Chatnavn';
$crl[19]='Besked';
$crl[20]='Gå Tilbage (150 linier)';
$crl[21]='Denne side kræver browser der understøtter Frames.';
$crl[22]='Brugere Online';
$crl[23]='Ingen Brugere Online...';
$crl[24]='Navn';
$crl[25]='Chat';
$crl[26]='Gå til Chatten [Genopfrisk]';
$crl[27]='Tilbage';
$crl[28]='Gå tilbage [Genopfrisk]';
$crl[29]='Log af';
$crl[30]='Log af [Skift Navn]';
$crl[31]='Ryd vinduet';
$crl[32]='Ryd hele chatten [Beskyttet med Kodeord]';
$crl[33]='Om';
$crl[34]='Genopfrisk: ';
?>
