<?php 
/* Croatian */

$crl[0]='4';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=windows-1250">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Zvuk: Pali/Gasi';
$crl[4]='Pošalji';
$crl[5]='Otkaži';
$crl[6]='Šifra';
$crl[7]='Promijeni boje...';
$crl[8]='LJUT';
$crl[9]='COOL';
$crl[10]='TUŽAN';
$crl[11]='VIČE';
$crl[12]='SMIJE SE';
$crl[13]='NAMIGUJE';
$crl[14]='BOLD';
$crl[15]='ITALIC';
$crl[16]='BOJA';
$crl[17]='Datum / Vrijeme';
$crl[18]='Nick';
$crl[19]='Poruka';
$crl[20]='HISTORY (150 linija)';
$crl[21]='Ova stranica zahtijeva browser koji podržava frameove.';
$crl[22]='Online korisnici';
$crl[23]='Nema online korisnika...';
$crl[24]='Nick';
$crl[25]='Chat';
$crl[26]='Prijeđi u chat [Refresh]';
$crl[27]='History';
$crl[28]='Prijeđi u history [Refresh]';
$crl[29]='LogOut';
$crl[30]='Log out [Promjena nicka]';
$crl[31]='Očisti';
$crl[32]='Očisti chat i history [Zaštićeno šifrom]';
$crl[33]='About';
$crl[34]='Refresh: ';
?>