<?php 
/* English */

$crl[0]='4';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">';
$crl[2]='K-Lore (Simple Chat 1.3)';
$crl[3]='Sound: On/Off';
$crl[4]='Submit';
$crl[5]='Cancel';
$crl[6]='Password';
$crl[7]='Change colors...';
$crl[8]='ANGRY';
$crl[9]='COOL';
$crl[10]='SAD';
$crl[11]='SHOUT';
$crl[12]='SMILE';
$crl[13]='WINK';
$crl[14]='BOLD';
$crl[15]='ITALIC';
$crl[16]='COLOR';
$crl[17]='Date / Time';
$crl[18]='Nickname';
$crl[19]='Message';
$crl[20]='HISTORY (150 lines)';
$crl[21]='This page requires a browser which supports frames.';
$crl[22]='Users Online';
$crl[23]='No Users Online...';
$crl[24]='Nick';
$crl[25]='Chat';
$crl[26]='Turn into chat [Refresh]';
$crl[27]='History';
$crl[28]='Turn into history [Refresh]';
$crl[29]='LogOut';
$crl[30]='Log out [Change nick]';
$crl[31]='Clear';
$crl[32]='Clear chat and history [password protected]';
$crl[33]='About';
$crl[34]='Refresh: ';
?>