<?php
/* German - thanks to Jens */

$crl[0]='34';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Sound: On/Off';
$crl[4]=' ok! ';
$crl[5]='abbrechen';
$crl[6]='Password';
$crl[7]='Farbe ändern...';
$crl[8]='böse';
$crl[9]='cool';
$crl[10]='traurig';
$crl[11]='rufen';
$crl[12]='lachen';
$crl[13]='zwinkern';
$crl[14]='fett';
$crl[15]='kursiv';
$crl[16]='farbe';
$crl[17]='Datum / Zeit';
$crl[18]='Name';
$crl[19]='Nachricht';
$crl[20]='-Verlauf (150 Zeilen)';
$crl[21]='This page requires a browser which supports frames.';
$crl[22]='Users Online';
$crl[23]='No Users Online...';
$crl[24]='Name';
$crl[25]='Chat';
$crl[26]='Chat [aktualisieren]';
$crl[27]='Verlauf';
$crl[28]='Chat-Verlauf [aktualisieren]';
$crl[29]='Verlassen';
$crl[30]='Chat verlassen [Name ändern]';
$crl[31]='Löschen';
$crl[32]='Chat-Verlauf löschen [Password geschützt]';
$crl[33]='über';
$crl[34]='aktualisieren: ';
?>