<?php 
/* Polish */

$crl[0]='4';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Dzwiek: On/Off';
$crl[4]='OK';
$crl[5]='Cofnij';
$crl[6]='Haslo';
$crl[7]='zmieñ kolor...';
$crl[8]='ANGRY';
$crl[9]='COOL';
$crl[10]='SAD';
$crl[11]='SHOUT';
$crl[12]='SMILE';
$crl[13]='WINK';
$crl[14]='BOLD';
$crl[15]='ITALIC';
$crl[16]='COLOR';
$crl[17]='Data / Czas';
$crl[18]='Nick';
$crl[19]='Tresc';
$crl[20]='HISTORIA (150 lini)';
$crl[21]='This page requires a browser which supports frames.';
$crl[22]='Zalogowanych na czacie';
$crl[23]='Brak zalogowanych...';
$crl[24]='Nick';
$crl[25]='Czat';
$crl[26]='Powrot na czat [odswiezanie]';
$crl[27]='Historia';
$crl[28]='Wroc do historii [odswiez]';
$crl[29]='Wyloguj';
$crl[30]='Wyloguj [zmien nick]';
$crl[31]='Wyczysc';
$crl[32]='Wyczysc czat i historie [chronione haslem]';
$crl[33]='Produkty';
$crl[34]='Odswiez: ';
?>
