<?php
/* Czech - pavel-at-kotrla-dot-com */

$crl[0]='48';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-2">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Sound: On/Off';
$crl[4]='Poslat';
$crl[5]='Zrušit';
$crl[6]='Heslo';
$crl[7]='Změnit barvy...';
$crl[8]='ROZHNĚVANÝ';
$crl[9]='V POHODĚ';
$crl[10]='SMUTNÝ';
$crl[11]='JÁSAJÍCÍ';
$crl[12]='USMĚVAVÝ';
$crl[13]='MHOUŘÍCÍ';
$crl[14]='TEXT TUČNĚ';
$crl[15]='TEXT KURZÍVOU';
$crl[16]='TEXT BAREVNĚ';
$crl[17]='Datum / Čas';
$crl[18]='Přezdívka';
$crl[19]='Zpráva';
$crl[20]='HISTORIE (150 řádků)';
$crl[21]='Tato stránka potřebuje prohlížeč s podporou rámců.';
$crl[22]='Přihlášení uživatelé';
$crl[23]='Žádní přihlášení uživatelé...';
$crl[24]='Přihlásit jako';
$crl[25]='Chat';
$crl[26]='Vstoupit do chatu [Aktualizovat]';
$crl[27]='Historie';
$crl[28]='Prohlédnout si historii [Aktualizovat]';
$crl[29]='Odhlásit';
$crl[30]='Odhlásit [Změnit přezdívku]';
$crl[31]='Vymazat';
$crl[32]='Vymazat chat a historii [chráněno heslem]';
$crl[33]='O chatu';
$crl[34]='Aktualizovat: ';
?>