<?php 
/* Thai */

$crl[0]='22';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=tis-620">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Sound: On/Off';
$crl[4]='ตกลง';
$crl[5]='ยกเลิก';
$crl[6]='รหัสผ่าน';
$crl[7]='เปลี่ยนสี...';
$crl[8]='โกรธ';
$crl[9]='สดชื่น';
$crl[10]='เสียใจ';
$crl[11]='ตะโกน';
$crl[12]='ยิ้ม';
$crl[13]='อิอิ';
$crl[14]='ตัวหนา';
$crl[15]='ตัวเอียง';
$crl[16]='สี';
$crl[17]='วันที่ / เวลา';
$crl[18]='ชื่อเล่น';
$crl[19]='ข้อความ';
$crl[20]='บันทึก (150 บันทัด)';
$crl[21]='This page requires a browser which supports frames.';
$crl[22]='Users Online';
$crl[23]='No Users Online...';
$crl[24]='ชื่อ';
$crl[25]='ห้องสนทนา';
$crl[26]='ห้องสนทนา';
$crl[27]='ข้อความย้อนหลัง';
$crl[28]='ดูข้อความย้อนหลัง';
$crl[29]='ออกจากระบบ';
$crl[30]='ออกจากห้องสนทนา';
$crl[31]='Admin';
$crl[32]='For Admin';
$crl[33]='About';
$crl[34]='รีเฟรชข้อความ : ';
?>