<?php 
/* Français */

$crl[0]='60';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Son: On/Off';
$crl[4]='Envoyer';
$crl[5]='Annuler';
$crl[6]='Mot de Passe';
$crl[7]='Changer les couleurs...';
$crl[8]='ANGRY';
$crl[9]='COOL';
$crl[10]='SAD';
$crl[11]='SHOUT';
$crl[12]='SMILE';
$crl[13]='WINK';
$crl[14]='GRAS';
$crl[15]='ITALIQUE';
$crl[16]='COULEUR';
$crl[17]='Date / Heure';
$crl[18]='Pseudo';
$crl[19]='Message';
$crl[20]='HISTORIQUE (150 lignes)';
$crl[21]='Cette page nécessite un navigateur acceptant les frames.';
$crl[22]='Utilisateurs en ligne ...';
$crl[23]='Aucun utilisateur en ligne ...';
$crl[24]='Pseudo';
$crl[25]='Chat';
$crl[26]='Entrer dans le chat [Rafraichir]';
$crl[27]='Historique';
$crl[28]='Entrer dans l\'historique [Rafraichir]';
$crl[29]='Sortir';
$crl[30]='Sortie [Changer de pseudo]';
$crl[31]='Effacer';
$crl[32]='Effacer le chat et l\'historique [nécessite un mot de passe]';
$crl[33]='A Propos';
$crl[34]='Rafraichir : ';
?>
