<?php 
/* Japanese */

$crl[0]='2';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=euc-jp">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Sound: On/Off';
$crl[4]='送信';
$crl[5]='キャンセル';
$crl[6]='パスワード';
$crl[7]='カラー変更...';
$crl[8]='怒';
$crl[9]='クール';
$crl[10]='悲';
$crl[11]='シャウト';
$crl[12]='スマイル';
$crl[13]='ウィンク';
$crl[14]='太字';
$crl[15]='斜体';
$crl[16]='カラー';
$crl[17]='日付 / 時刻';
$crl[18]='ニックネーム';
$crl[19]='メッセージ';
$crl[20]='履歴 (150 行)';
$crl[21]='このページはフレーム対応のブラウザでご覧下さい。';
$crl[22]='Users Online';
$crl[23]='No Users Online...';
$crl[24]='ログイン';
$crl[25]='チャット';
$crl[26]='チャットを更新';
$crl[27]='履歴';
$crl[28]='履歴を更新';
$crl[29]='ログアウト';
$crl[30]='ログアウト [ニックネーム変更]';
$crl[31]='クリア';
$crl[32]='履歴を削除 [パスワード必要]';
$crl[33]='About';
$crl[34]='更新: ';
?>