<?php 
/* Portugues - Brasil  traducao efetuada por Gustavo Mendes de Carvalho - gmcarvalho@yahoo.com */

$crl[0]='5';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Som: On/Off';
$crl[4]='Envia';
$crl[5]='Cancela';
$crl[6]='Senha';
$crl[7]='Troca cores...';
$crl[8]='Bravo';
$crl[9]='Legal';
$crl[10]='Triste';
$crl[11]='Grito';
$crl[12]='Sorriso';
$crl[13]='Piscadinha';
$crl[14]='Negrito';
$crl[15]='Italico';
$crl[16]='Cor';
$crl[17]='Data / Hora';
$crl[18]='Apelido';
$crl[19]='Mensagem';
$crl[20]='Historico (150 linhas)';
$crl[21]='Esta pagina precisa de um browser que suporte frames.';
$crl[22]='Usuarios Online';
$crl[23]='Sem Usuarios Online...';
$crl[24]='Apelido';
$crl[25]='Chat';
$crl[26]='Modo chat [Atualiza]';
$crl[27]='Historico';
$crl[28]='Modo historico [Atualiza]';
$crl[29]='Sair';
$crl[30]='Log out [Muda apelido]';
$crl[31]='Limpar';
$crl[32]='Limpar chat e historico [necessita senha]';
$crl[33]='Sobre';
$crl[34]='Atualiza:';
?>

