<?php 
/* Nederlands - thanks to Jeroen */

$crl[0]='48';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Sound: On/Off';
$crl[4]='Post';
$crl[5]='Cancel';
$crl[6]='Paswoord';
$crl[7]='Verander kleur...';
$crl[8]='KWAAD';
$crl[9]='RELAXED';
$crl[10]='TREURIG';
$crl[11]='SCHREEUW';
$crl[12]='LACH';
$crl[13]='KNIPOOG';
$crl[14]='Vet';
$crl[15]='Italic';
$crl[16]='Kleur';
$crl[17]='Datum / tijd';
$crl[18]='Nickname';
$crl[19]='Bericht';
$crl[20]='Geschiedenis (150 regels)';
$crl[21]='Om deze pagina te zien heeft u een browser nodig die frames ondersteund.';
$crl[22]='Users Online';
$crl[23]='No Users Online...';
$crl[24]='Nick';
$crl[25]='Chat';
$crl[26]='Verander in chat [Refresh]';
$crl[27]='Geschiedenis';
$crl[28]='Verander in geschiedenis [Refresh]';
$crl[29]='Uitloggen';
$crl[30]='Uitloggen [verander nick]';
$crl[31]='Wis';
$crl[32]='Wis chat en geschiedenis [paswoord beveiligd]';
$crl[33]='About';
$crl[34]='Refresh: ';
?>