<?php 
/* Hungarian - SimpleChat@milliomos.com */

$crl[0]='4';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">';
$crl[2]='Simple Chat';
$crl[3]='Hang: Be/Ki';
$crl[4]='Küld';
$crl[5]='Töröl';
$crl[6]='Jelszó';
$crl[7]='Szín cseres...';
$crl[8]='Bosszús';
$crl[9]='Hûvös';
$crl[10]='Bús';
$crl[11]='Ordít';
$crl[12]='Mosoly';
$crl[13]='Kacsint';
$crl[14]='Vastag';
$crl[15]='Dõlt betûs';
$crl[16]='Szín';
$crl[17]='Dátum / Idõ';
$crl[18]='Becenév';
$crl[19]='Üzenet';
$crl[20]='Elõzõ (150 hozzászólás)';
$crl[21]='Keretes böngészõ kell...';
$crl[22]='Felhasználó kapcsolatban';
$crl[23]='Nincs jelen felhasználó...';
$crl[24]='Nick';
$crl[25]='Csevegõ';
$crl[26]='Frissít';
$crl[27]='ELõzmény';
$crl[28]='Megnéz';
$crl[29]='Kijelentkezés';
$crl[30]='Nik csere!';
$crl[31]='Törlés';
$crl[32]='Adatfájl törlése [csak admin]';
$crl[33]='Névjegy';
$crl[34]='Frissít: ';
?>
