<?php 
/* Swedish */

$crl[0]='4';
$crl[1]='<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">';
$crl[2]='SimpleChat! 1.3';
$crl[3]='Ljud: På/Av';
$crl[4]='Skicka';
$crl[5]='Avbryt';
$crl[6]='Lösenord';
$crl[7]='Ändra färger...';
$crl[8]='ARG';
$crl[9]='COOL';
$crl[10]='LEDSEN';
$crl[11]='GAPA';
$crl[12]='LE';
$crl[13]='FLIRTA';
$crl[14]='FET';
$crl[15]='KURSIV';
$crl[16]='FÄRG';
$crl[17]='Datum / Tid';
$crl[18]='Namn';
$crl[19]='Meddelanden';
$crl[20]='HISTORIA (150 rader)';
$crl[21]='Denna sida kräver en webbläsare som hanterar ramar.';
$crl[22]='Användare Online';
$crl[23]='Inga användare Online...';
$crl[24]='Namn';
$crl[25]='Chatt';
$crl[26]='Växla till chatt [Uppdatera]';
$crl[27]='Historia';
$crl[28]='Växla till historia [Uppdatera]';
$crl[29]='Logga Ut';
$crl[30]='Logga ut [Ändra namn]';
$crl[31]='Rensa';
$crl[32]='Rensa chatt och historia [Lösenordsskyddat]';
$crl[33]='Om';
$crl[34]='Uppdatera: ';
?>